### ISSUE TITLE
Help with maintenance?

### ISSUE THREAD

**Issue by rtobar** [WhyNotHugo/sphinx-autorun#62]
Hi @WhyNotHugo ,

I'm approaching to ask whether you'd be happy to receive some amount of help with minor maintenance of this extension? We use it in [Spanish translation of Python documentation](https://github.com/python/python-docs-es/), and I found a couple of things I'd want to fix/add.

I saw the project is dormant since 2019 though. If you could quickly respond your plans for maintenance (from dedicating zero time, to doing some maintenance work, to even hand over PyPI ownership, no pressure in no direction of course) that'd be great, and would inform us to whether we could continue relying on this extension, or whether we move to using a different solution.

Thanks!

**Comment by WhyNotHugo** [comment]
Bugfixes or tweaks for compatibility are welcome.

There hasn't been much activity since this hasn't broken in existing usages.

**Comment by rtobar** [comment]
Thanks @WhyNotHugo, that's very helpful feedback. In that case I'll work on submitting a couple of PRs and see if they are deemed useful. Thanks!
