### ISSUE TITLE
All ".. runblock:: pycon" blocks start with new line

### ISSUE THREAD

**Issue by lgarcin** [WhyNotHugo/sphinx-autorun#8]
First of all, thank for your work.
I noticed a bug in the output of `runblock` directives ; I think the title of the issue is self-explanatory.

For example
```
.. runblock:: pycon

    >>> a = 0
    >>> a += 1
    >>> a
```
produces
```

>>> a = 0
>>> a += 1
1
```
I'd like to get rid of the leading newline.

**Comment by hobarrera** [comment]
Good catch, I'll try and look into this in the next days.

**Comment by endrebak** [comment]
+1 on this.

**Comment by endrebak** [comment]
I uploaded a new version to PyPI called `sphinx_autorun_ebs` which I can personalize to my needs, but I do not mind making PRs here.

**Comment by torfsen** [comment]
I just ran into this in the current version (1.1.0). Could you prepare a new release which contains the bugfix?

**Comment by vaneseltine** [comment]
Yes, this has been fixed for a while -- it'd be great to have it released to PyPI.

**Comment by WhyNotHugo** [comment]
I'll try to get that pushed through during the day today :)

**Comment by WhyNotHugo** [comment]
Aw, dammit. The push fails. Looks like CI still also runs Python 3.3, gonna have to update that.

**Comment by WhyNotHugo** [comment]
Published for real this time!

**Comment by vaneseltine** [comment]
Thanks!
